
spring:
  # 配置数据源信息
  datasource:
    # 配置数据源类型
    type: com.zaxxer.hikari.HikariDataSource
    # 配置连接数据库信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.15.250:3306/database?characterEncoding=utf8&useSSL=false
    username: root
    password: Y@unj12^ncHb)nbh

# 在生产环境关闭Swagger文档
springfox:
  documentation:
    swagger-ui:
      enabled: false